data<-read.table("household_power_consumption.txt", header=T, sep=";")
data$DateTime <- as.POSIXct(paste(data$Date, data$Time,sep=" "), format="%d/%m/%Y %H:%M:%S")
d<-subset(data,data$DateTime>='2007-02-01'&data$DateTime<'2007-02-03')
s1<-as.numeric(as.character(d$Sub_metering_1))
s2<-as.numeric(as.character(d$Sub_metering_2))
s3<-as.numeric(as.character(d$Sub_metering_3))
png(filename = "plot3.png",width = 480, height = 480)
plot(d$DateTime,s1,type='n',xlab="",ylab='Energy sub metering')
lines(d$DateTime,s1,col='black')
lines(d$DateTime,s2,col='red')
lines(d$DateTime,s3,col='blue')
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
dev.off()
